name: todo_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_screenutil: ^5.5.4
  easy_localization: ^3.0.0
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  path_provider: ^2.1.1
  path: ^1.8.3
  freezed: ^2.4.1
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  progress_indicators: ^1.0.0
  bloc: ^8.1.2
  sqflite: ^2.3.0 
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  built_value_generator: ^8.6.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translation/
    - assets/icons/svg/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
